cargo-features = ["per-package-target"]

[workspace]
members = ["crates/cybercmd", "crates/xtask", "crates/test", "crates/common"]

[workspace.dependencies]
cybercmd = { path = "crates/cybercmd" }
test = { path = "crates/test" }
xtask = { path = "crates/xtask" }
common = { path = "crates/common" }
log = "0.4"
anyhow = "1"
once_cell = "1"
thiserror = "1"
xshell = "0.2"
clap = { version = "4", features = ["cargo"] }
reqwest = "0.11"
zip = "0.6"
zip-extensions = { git = "https://github.com/AndASM/zip-extensions-rs.git", tag = "v0.6.2" }
normpath = "1"
winapi = { version = "0.3" }
widestring = "1"
uniquote = "3.3.0"
microtemplate = "1"
toml = "0.7"
chrono = "0.4.24"
log4rs = "1.2.0"
serde = { version = "1", features = ["derive"] }
detour = { git = "https://github.com/veeenu/detour-rs", rev = "ec23632" }

[profile.release]
lto = true
strip = true
