[package]
name = "cybercmd"
version = "0.0.7"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
detour = { git = "https://github.com/veeenu/detour-rs", rev = "ec23632" }
winapi = { version = "0.3", features = ["minwindef", "winnt", "libloaderapi"] }
widestring = "1"
once_cell = "1"
microtemplate = "1"
toml = "0.7"
serde = { version = "1", features = ["derive"] }
anyhow = "1"

[profile.release]
lto = true
strip = true
