[package]
name = "cybercmd"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
detour = "0.8"
winapi = { version = "0.3", features = ["minwindef", "winnt", "libloaderapi"] }
widestring = "0.5"
once_cell = "1.12"
microtemplate = "1"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1"
