# The [args] section is optional. It defines commandline arguments for cyberpunk2077.exe.
# Known arguments are defined as commented-out examples below.
[args]
unattended = "true"
forceRawTweakDB = "true"
profiler = "true"
# disableRayTracing = "true"
# disableRayTracedReflection = "true"
# disableRayTracedTransparentReflection = "true"
# dlss = "true"
# windowCaption = "Cyberbug 2077"
# scriptVersion = "Debug" | "Profiling" | "Final" | "Final_noopts"
# tweakdbBlobPath = "{game_dir}\r6\cache\tweakdb.bin"
# scriptsBlobPath = "{game_dir}\r6\cache\final.redscripts"
# pvdDumpToFile = "true"
# renderPreset = "Game" | "User"
# engine = "BackendGameEngine"
# interopstartingport = ?
# watchdogTimeout = ?
# automator = ?

# gameDefinition = "base\quest\test\farm_bd_perf.gamedef"
# world = ?
# startSpawnPoint = ?
# startPosition = ?
# startRotation = ?
# startQuest = ?
# playerGender = "Male" | "Female"
# alwaysSpawnedDisabled = "true"
# forceSpawnInView = "true"
# entitySpawnRadius = 100.0
# noCrowd = "true"
# noReducedCrowd = "true"
# ignoreSavedCensorFlags = "true"
# benchmark = "true"

# mainmenu = "false"
# autojoin = "true"
# server = "127.0.0.1"
# sessionType = "LAN" | "Internet"
# playerRecordID = ?
# sessionLength = ?
# state = ?
# save = "AutoSave-0"
# forceShutdownAfterSessionLoaded = "true"
# skipStartScreen = "true"
# modded = "true"

# A cybercmd config file can optionally have one or more [[tasks]] sections.
# These define tasks to be automatically run just before cyberpunk2077.exe
# For example, the redscript compile scc.exe is run to compile mod scripts.
# See `examples/task.toml` for more.
#
# [[tasks]]
# command = "InvokeScc"
# terminate_on_errors = false
# no_window = true
# template_args = ["-compile", "{path}", "-customCacheDir", "{custom_cache_dir}"]
# substitutions.path = "{game_dir}\\r6\\scripts"
# substitutions.custom_cache_dir = "{game_dir}\\r6\\cache\\modded"
