name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Release and upload artifacts
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cybercmd
      - name: Add rust-src component for build-std
        run: rustup component add rust-src --toolchain nightly
      - run: cargo xtask dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/dist/cybercmd-standalone.zip
            target/dist/cybercmd.zip
