name: Create Release Artifacts
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_INCREMENTAL: 0 # Incremental not supported by our caching
  CARGO_TERM_COLOR: always # GH action logs support terminal colors
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse # New format as of 2023-03-09

jobs:
  build-release:
    name: Build and create release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cybercmd
          cache-on-failure: true
      - run: cargo xtask dist
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{  github.ref_name }} --generate-notes $(Resolve-Path -Relative -Path ./target/dist/*.zip)
